---
version: "2"
linters:
  # Default: standard
  default: all
  # Enable specific linter.
  enable:
    - modernize
    - wsl_v5
    - revive
  disable:
    - depguard
    - funlen
    - wsl
    - varnamelen
    - paralleltest
    - wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    revive:
      rules:
        - name: var-naming
          severity: warning
          arguments:
            - ["ID", "URL"]
    exhaustruct:
      exclude:
        - 'gorm\.io/gorm\.Config$'
        - 'gorm\.io/gorm/schema\.Schema$'
  exclusions:
    rules:
      - path: '_test\.go$'
        linters:
          - paralleltest
          - cyclop
          - gocognit
          - noctx
          - noinlineerr
          - exhaustruct
          - mnd
          - nestif
          - lll
          - godot
          - errchkjson
          - wsl_v5
